[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_staking_contract = "6zduDhgP3sgsqTG4yzcqerRj28dtMbjrhsnidyfSRnow"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/harry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
